Add python-billiard to pulp-scl
pulp/packaging pull request #37
Opened 2016-11-09 19:56 UTC by pcreech

Add python-billiard to pulp's scl

re #[2338](https://pulp.plan.io/issues/2338)

2016-11-14 21:36 UTC, werwty requested changes

2016-11-14 21:36 UTC, werwty commented on rpms/pulp-scl-python-billiard/pulp-scl-python-billiard.spec
> +BuildRequires:	%{?scl_prefix_python}python-nose
Do we need python-nose in order to build? This seems to be more of a devel dependency...

2016-11-14 21:36 UTC, werwty commented on rpms/pulp-scl-python-billiard/pulp-scl-python-billiard.spec
> +BuildRoot:      %{_tmppath}/%{pkg_name}-%{version}-%{release}-root-%(%{__id_u} -n)
I'm not sure if we need this. I'm not seeing this being referenced to in the build log. And according to https://fedoraproject.org/wiki/How_to_create_an_RPM_package

> BuildRoot: This is where files will be "installed" during the %install process (after the %build process). This is now redundant in Fedora and is only needed for EPEL5. By default, the build root is placed in "%{_topdir}/BUILDROOT/".

2016-11-15 13:59 UTC, pcreech commented on rpms/pulp-scl-python-billiard/pulp-scl-python-billiard.spec
> +BuildRoot:      %{_tmppath}/%{pkg_name}-%{version}-%{release}-root-%(%{__id_u} -n)
Correct, we don't.  I removed the overridden build root lines from other pakcages, it appears I left it in here

2016-11-15 14:02 UTC, pcreech commented on rpms/pulp-scl-python-billiard/pulp-scl-python-billiard.spec
> +BuildRequires:	%{?scl_prefix_python}python-nose
Should be able to remove, as we don't do anything with %check, for now at least.

2016-11-17 19:01 UTC, werwty approved these changes

2016-11-17 19:02 UTC, merged